issue/10 - Add ajax search to products dropdown
AffiliateWP/affiliatewp-affiliate-product-rates pull request #35
Opened 2020-12-19 01:15 UTC by dbeja

Issue #10 

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

**Changes**
* Upgraded select2 script to the latest version
* Products dropdown is now dynamic and searchable via ajax. No limit on the number of products.
* When selected it will load with ajax 100 products
* When the list is scrolled down, it will get more pages of products if it exists (infinite scrolling)
* Any terms entered it will search with ajax on the database

**Before changes**
![image](https://user-images.githubusercontent.com/498472/102676802-26196e00-4197-11eb-81d7-f0d3bda3a586.png)

**After changes**
Just 2 minor differences: rounded corners and a bit more padding on the input.
As it seems to look better, I didn't force to be exactly as before.
![image](https://user-images.githubusercontent.com/498472/102676834-4a754a80-4197-11eb-9a2a-a0437c7a86a2.png)

2021-01-28 18:38 UTC, dbeja commented
@DrewAPicture Should I also add Andrew here as a reviewer?

2021-01-29 00:40 UTC, DrewAPicture commented
> @DrewAPicture Should I also add Andrew here as a reviewer?

Yes please.

2021-02-17 02:48 UTC, amdrew approved these changes
Seems to work great in my testing. It's nice how when you scroll down the list it loads more and more. I was able to load all 400+ of my EDD products inside the dropdown without issue:

👍 from me

<img width="949" alt="Screen Shot 2021-02-17 at 3 46 32 PM" src="https://user-images.githubusercontent.com/52581/108149370-914fd400-7137-11eb-8123-0d7f70572225.png">

2021-02-17 04:00 UTC, DrewAPicture requested changes

2021-02-17 04:00 UTC, DrewAPicture commented on includes/scripts.php
> +	$rest_url = rest_url( 'affwp_pr/v1/products' );
Need to update the REST route here as well.

2021-02-17 15:40 UTC, dbeja commented
@DrewAPicture, REST routes updated.

2021-02-17 16:55 UTC, DrewAPicture approved these changes

2021-06-14 10:30 UTC, merged